/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define HIGH 		(1)
#define PRESSED		HIGH
void delay(void)
{
	for (uint32_t i = 0; i<500000; i++);
}

int main(void)
{
	GPIO Led(GPIOC, GPIO_PIN_NO_13, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_FREQ_LOW, NONE);

	while(1)
	{
		delay();
		Led.GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
	}
	return 0;
}
