/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define HIGH 		(1)
#define PRESSED		HIGH
void delay(void);





int main(void)
{
	GPIO Led(GPIOC, GPIO_PIN_NO_13, GPIO_MODE_OUTPUT_PP, GPIO_SPEED_FREQ_LOW, NONE);
	GPIO Button (GPIOB, GPIO_PIN_NO_1, GPIO_IN_IT_RT, NONE, GPIO_PULLDOWN);
	Led.GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_13, GPIO_PIN_SET);
	GPIO_IRQPriorityConfig(GPIO_PIN_NO_1, NVIC_IRQ_PRI0);
	GPIO_IRQInterruptConfig(GPIO_PIN_NO_1, ENABLE);
	while(1);
}

void EXTI1_IRQHandler(void)
{
	delay();
	GPIO_IRQHandling(GPIO_PIN_NO_1);
	GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
}

void delay(void)
{
	for (uint32_t i = 0; i<500000; i++);
}

